-- Migration number: 0011	2025-08-14T19:11:45.155Z
-- CreateTable
CREATE TABLE "foodItems"
(
    "id"                          TEXT    NOT NULL PRIMARY KEY,
    "userId"                      TEXT    NOT NULL,
    "name"                        TEXT    NOT NULL,
    "servingSize"                 INTEGER NOT NULL,
    "totalFat"                    INTEGER,
    "saturatedFat"                INTEGER,
    "transFat"                    INTEGER,
    "unsaturatedFat"              INTEGER,
    "cholesterol"                 INTEGER,
    "sodium"                      INTEGER,
    "totalCarbohydrates"          INTEGER,
    "dietaryFiber"                INTEGER,
    "sugar"                       INTEGER,
    "starch"                      INTEGER,
    "protein"                     INTEGER,
    "totalCalories"               INTEGER,
    "caloriesFromUnsaturatedFats" INTEGER,
    "caloriesFromProteins"        INTEGER,
    "caloriesFromComplexCarbs"    INTEGER,
    "totalHealthyCalories"        INTEGER,
    "calorieScore"                REAL,
    "vitaminA"                    REAL,
    "vitaminB6"                   REAL,
    "vitaminC"                    REAL,
    "vitaminE"                    REAL,
    "calcium"                     REAL,
    "riboflavin"                  REAL,
    "phosphorus"                  REAL,
    "zinc"                        REAL,
    "iron"                        REAL,
    "thiamin"                     REAL,
    "niacin"                      REAL,
    "folate"                      REAL,
    "magnesium"                   REAL
);