/* eslint-disable cspell/spellchecker */
export const youtubeChannels = [
  { channelId: "UCSJbGtTlrDami-tDGPUV9-w", name: "Academind" },
  { channelId: "UC3cEGKhg3OERn-ihVsJcb7A", name: "Angular University" },
  { channelId: "UC0pEW_GOrMJ23l8QcrGdKSw", name: "Apollo GraphQL" },
  { channelId: "UC9PIn6-XuRKZ5HmYeu46AIw", name: "Barely Sociable" },
  { channelId: "UClynm5rx2oyGT2a1VlRC3kA", name: "Bellwright" },
  { channelId: "UC-8QAzbLcRglXeN_MY9blyw", name: "Ben Awad" },
  { channelId: "UCDXTQ8nWmx_EhZ2v-kp7QxA", name: "Ben Felix" },
  { channelId: "UC2Xd-TjJByJyK2w1zNwY0zQ", name: "Beyond Fireship" },
  { channelId: "UCcMjLgeWNwqL2LBGS-iPb1A", name: "Bishop Robert Barron" },
  { channelId: "UCijn3WBpHtx4AvSya7NER9Q", name: "BLS Videos" },
  { channelId: "UCZljytO0sLrlTswP0sPkRkg", name: "BradWOTO" },
  { channelId: "UCOHxDwCcOzBaLkeTazanwcw", name: "Bravos Research" },
  { channelId: "UCQMjMW-9PhWoH6TWwmnVWvA", name: "CallMeCarson" },
  { channelId: "UCEOXxzW2vU0P-0THehuIIeg", name: "Captain Disillusion" },
  { channelId: "UCtinbF-Q-fVthA0qrFQTgXQ", name: "CaseyNeistat" },
  { channelId: "UC2C_jShtL725hvbm1arSV9w", name: "CGP Grey" },
  { channelId: "UCU_W0oE_ock8bWKjALiGs8Q", name: "Charisma on Command" },
  { channelId: "UCK44H7LgmSSiQdehlxBGwRg", name: "ChristianStory" },
  { channelId: "UCnUYZLuoy1rq1aVMwx4aTzw", name: "Chrome for Developers" },
  { channelId: "UC0e3QhIYukixgh5VVpKHH9Q", name: "Code Bullet" },
  { channelId: "UCFQMnBA3CS502aghlcr0_aw", name: "Coffeezilla" },
  { channelId: "UC4QZ_LsYcvcq7qOsOhpAX4A", name: "ColdFusion" },
  { channelId: "UCrqAGUPPMOdo0jfQ6grikZw", name: "Colt Steele" },
  { channelId: "UCtw7q4SyOeoCwM1i_3x8lDg", name: "Comedy Central Stand-Up" },
  { channelId: "UC9-y-6csu5WGm29I7JiwpnA", name: "Computerphile" },
  { channelId: "UCuZPtWDsczOuztPMUr0mmpw", name: "CORPSE" },
  { channelId: "UCFNTq9XKHDNy_1-2lL0kqCg", name: "Corpse Husband" },
  { channelId: "UCsUalyRg43M8D60mtHe6YcA", name: "CultRepo" },
  { channelId: "UC0A9YrHgD5hZ2JXQrxRPHsw", name: "Daily Dose Of Wisdom" },
  { channelId: "UCKZXMa9trFmNTAoGKM-_wfg", name: "David JP Phillips" },
  { channelId: "UCVo63lbKHjC04KqYhwSZ_Pg", name: "Defunctland" },
  { channelId: "UCWQaM7SpSECp9FELz-cHzuQ", name: "Dreams of Code" },
  { channelId: "UCPDXXXJj9nax0fr0Wfc048g", name: "Dropout" },
  { channelId: "UCKTwTio3tOv713CnIcxyLhA", name: "Dungeon Soup" },
  { channelId: "UCuo9VyowIT-ljA5G2ZuC6Yw", name: "Eddy Burback" },
  { channelId: "UC7Ucs42FZy3uYzjrqzOIHsw", name: "EmpLemon" },
  { channelId: "UCVXKabRhXSQXh_U0au5JSzQ", name: "EWU Crime Storytime" },
  { channelId: "UCJWKjrrUh2KL1d3zXQW79cQ", name: "EXPLORE WITH US" },
  { channelId: "UCsBjURrPoezykLs9EqgamOA", name: "Fireship" },
  { channelId: "UCWF8SqJVNlx-ctXbLswcTcA", name: "FoundMyFitness" },
  { channelId: "UCbWcXB0PoqOsAvAdfzWMf0w", name: "Fredrik Knudsen" },
  { channelId: "UCQUicR6JrQjRXse6x4M6lvw", name: "Full Fat Videos" },
  { channelId: "UCqJ-Xo29CKyLTjn6z2XwYAw", name: "Game Maker's Toolkit" },
  { channelId: "UC4PooiX37Pld1T8J5SYT-SQ", name: "Good Mythical Morning" },
  { channelId: "UCK8sQmJBp8GCxrOtXWBpyEA", name: "Google" },
  { channelId: "UCs_tLP3AiwYKwdUHpltJPuA", name: "GOTO Conferences" },
  { channelId: "UCV6KDgJskWaEckne5aPA0aQ", name: "Graham Stephan" },
  { channelId: "UCCxw3NMP8-2BtgRgIjjLo_A", name: "Harland Highway Podcast" },
  { channelId: "UCgdeMp2ZBnovi12THmLc47g", name: "Harry Wolff" },
  { channelId: "UClt01z1wHHT7c5lKcU8pxRQ", name: "hbomberguy" },
  { channelId: "UClHVl2N3jPEbkNJVx-ItQIQ", name: "HealthyGamerGG" },
  { channelId: "UCR4s1DE9J4DHzZYXMltSMAg", name: "HowToBasic" },
  { channelId: "UC8Q7XEy86Q7T-3kNpNjYgwA", name: "Incognito Mode" },
  {
    channelId: "UCyWDmyZRjrGHeKF-ofFsT5Q",
    name: "Internet Comment Etiquette with Erik",
  },
  { channelId: "UCR1D15p_vdP3HkrH8wgjQRw", name: "Internet Historian" },
  { channelId: "UCuriCa9loP_OsH75_5j8M5w", name: "JablinskiGames" },
  { channelId: "UC6vRUjYqDuoUsYsku86Lrsw", name: "Jack Herrington" },
  { channelId: "UC8bRyfU7ycLXnEBfvdorpUg", name: "Jamstack TV" },
  { channelId: "UCGp4UBwpTNegd_4nCpuBcow", name: "JetBrains" },
  { channelId: "UCMUyG01MXNeiTykIlvWwIRQ", name: "JJJacksfilms" },
  { channelId: "UCkqcY4CAuBFNFho6JgygCnA", name: "Jocko Podcast" },
  { channelId: "UCVIFCOJwv3emlVmBbPCZrvw", name: "Joel Haver" },
  { channelId: "UCFl7yKfcRcFmIUbKeCA-SJQ", name: "Joji" },
  { channelId: "UCdJdEguB1F1CiYe7OEi3SBg", name: "JonTronShow" },
  { channelId: "UCL_f53ZEJxp8TtlOkHwMV9Q", name: "Jordan B Peterson" },
  { channelId: "UCqYPhGiB9tkShZorfgcL2lA", name: "Joseph Everett–WIL" },
  { channelId: "UCJjSDX-jUChzOEyok9XYRJQ", name: "Jubilee" },
  { channelId: "UCx0L2ZdYfiq-tsAXb8IXpQg", name: "Just Write" },
  { channelId: "UCzOEJREOXANNXcFf2OP8hZg", name: "Kassem G" },
  { channelId: "UCwzCMiicL-hBUzyjWiJaseg", name: "Kill Tony" },
  { channelId: "UCm22FAXZMw1BaWeFszZxUKw", name: "Kitboga" },
  { channelId: "UCsXVk37bltHxD1rDPwtNM8Q", name: "Kurzgesagt–In a Nutshell" },
  { channelId: "UCMbvTF91O--bhwmg9dTMAPA", name: "Lyle Forever" },
  { channelId: "UC7_YxT-KID8kRbqZo7MyscQ", name: "Markiplier" },
  { channelId: "UCswG6FSbgZjbWtdf_hMLaow", name: "Matt Pocock" },
  { channelId: "UCNxUdsuH8-kEGIwSD0r8RhQ", name: "Maximilian Schwarzmüller" },
  { channelId: "UC91V6D3nkhP89wUb9f_h17g", name: "MeatCanyon" },
  { channelId: "UCwhB8cJTSLxyubnKSS-PLJg", name: "MegaLag" },
  { channelId: "UCeYvzUfpNSGnzasUjNKIA_w", name: "Mike Clum" },
  {
    channelId: "UCCfqyGl3nq_V0bo64CjZh8g",
    name: "Modern Software Engineering",
  },
  { channelId: "UCxfr3b8IuHSzu22UHnAvHWg", name: "MoistCr1TiKaL Gaming" },
  { channelId: "UCehBVAPy-bxmnbNARF-_tvA", name: "More Perfect Union" },
  { channelId: "UCvIOEFJvQSx-BH6Ln3uOYDg", name: "My Trucking Skills" },
  { channelId: "UC8h8NJG9gacZ5lAJJvhD0fQ", name: "NardwuarServiette" },
  { channelId: "UCxsQFG_8Dbt1sZhLReL2mUw", name: "Nerd City" },
  { channelId: "UCJkMlOu7faDgqh4PfzbpLdg", name: "Nerdwriter1" },
  { channelId: "UCdcUmdOxMrhRjKMw-BX19AA", name: "Niko Omilana" },
  { channelId: "UCxM_HSd0knTh15jnh_-8Gxw", name: "Not Exactly Normal" },
  { channelId: "UCWTFGPpNQ0Ms6afXhaWDiRw", name: "Now You See It" },
  { channelId: "UCoxcjq-8xIDTYp3uz647V5A", name: "Numberphile" },
  { channelId: "UCDstQZHA9T8-ZP046R0KEXA", name: "OfferZen Origins" },
  { channelId: "UCYF1kiTFCcYPqGTqXKt3JJg", name: "Papa Meat" },
  { channelId: "UC-wXkB3v0N9MB2Y9rR2Pbkg", name: "PartiallyRoyal" },
  { channelId: "UC-mP1nlk0qOutA08zuQHORA", name: "Patrick Cc:" },
  { channelId: "UCq6VFHwMzcMXbuKyG7SQYIg", name: "penguinz0" },
  { channelId: "UC-lHJZR3Gqxm24_Vd_AJ5Yw", name: "PewDiePie" },
  { channelId: "UCzQUP1qoWDoEbmsQxvdjxgQ", name: "PowerfulJRE" },
  { channelId: "UCqvaXJ1K3HheTPNjH-KpwXQ", name: "Principles by Ray Dalio" },
  { channelId: "UCptAHlN1gdwD89tFM3ENb6w", name: "Prisma" },
  { channelId: "UC4JpFaR7m3AOiVHlenk9fqA", name: "Proton" },
  { channelId: "UCz_cDc_2arKIb6SlJoqFT0w", name: "RackaRacka" },
  { channelId: "UCcEDTBdietc2JmgN6TL8wAg", name: "Radical Discourse" },
  { channelId: "UCTzpYUtxLlWs-wtQP19X7Aw", name: "Ranton" },
  {
    channelId: "UCsFrt8oKNYXGspSlX9u6uXw",
    name: "React Conferences by GitNation",
  },
  { channelId: "UCBobKKmkDPL_5Vr9-OxveZQ", name: "ReacThing" },
  { channelId: "UCgL3tdpvoARHuX-_3eLWEgg", name: "Real World React" },
  { channelId: "UCbochVIwBCzJb9I2lLGXGjQ", name: "Rhett & Link’s Wonderhole" },
  { channelId: "UCktMB3gUgaHW0lZGGim5aMQ", name: "Rittz" },
  { channelId: "UCLLVlcmcCP4CUe7xSqVEnxw", name: "Ryan Carniato" },
  { channelId: "UCNYrK4tc5i1-eL8TXesH2pg", name: "schmoyoho" },
  { channelId: "UCV9_KinVpV-snHe3C3n1hvA", name: "shane" },
  { channelId: "UCY30JRSgfhYXA6i6xX1erWg", name: "Smosh" },
  { channelId: "UCPJHQ5_DLtxZ1gzBvZE99_g", name: "Smosh Alike" },
  { channelId: "UCJ2ZDzMRgSrxmwphstrm8Ww", name: "Smosh Games" },
  { channelId: "UCYJPby9DRCteedh5tfxVbrw", name: "Smosh Pit" },
  { channelId: "UCEyodonqP_80YrDvattntmw", name: "SmoshCast" },
  { channelId: "UC60sV1b2e_EQRDnueRxgiIQ", name: "Soup Emporium" },
  { channelId: "UCuL3xV8AqD3sekKOhhyZqOA", name: "Straight Arrow News" },
  { channelId: "UCJZ0pbf29b2nrLde-a-LuDQ", name: "Streetcraft" },
  { channelId: "UCTeYrzSQ3YCp3RovGH4y8Ew", name: "Strong Towns" },
  { channelId: "UCZpWMxP4e8sQLZjbYQmanIw", name: "Sundays with Ascension" },
  { channelId: "UCR5v53B9L8lDvKScYrv1MUA", name: "Surma" },
  { channelId: "UCT5C7yaO3RVuOgwP8JVAujQ", name: "Taskmaster" },
  { channelId: "UCsooa4yRKGN_zEE8iknghZA", name: "TED-Ed" },
  { channelId: "UCBXOFnNTULFaAnj24PAeblg", name: "The Chosen" },
  { channelId: "UCKfak8fBm_Lhy4eX9UKxEpA", name: "The Military Show" },
  { channelId: "UCRHXUZ0BxbkU2MYZgsuFgkQ", name: "The Spiffing Brit" },
  { channelId: "UC5AQEUAwCh1sGDvkQtkDWUQ", name: "Theo Von" },
  { channelId: "UCBa659QWEk1AI4Tg--mrJ2A", name: "Tom Scott" },
  { channelId: "UCDKJdFer1phQI95UinPZehw", name: "Turkey Tom" },
  { channelId: "UCbAn7pVK2VIyo-UysfWGdZQ", name: "ui․dev" },
  { channelId: "UCJnidRIv3o1hf_YBWjKFljg", name: "Una Kravets" },
  { channelId: "UCHnyfMqiRRG1u-2MsSQLbXA", name: "Veritasium" },
  { channelId: "UCsvn_Po0SmunchJYOWpOxMg", name: "videogamedunkey" },
  { channelId: "UCUrdmVprSahXaPKqr04VfgQ", name: "VoiceOfThunder" },
  { channelId: "UCqmugCqELzhIMNYnsjScXXw", name: "Vsauce2" },
  { channelId: "UCoebwHSTvwalADTJhps0emA", name: "Wes Bos" },
  { channelId: "UCJX2EazMKUqBQV048px2aoA", name: "Wes Huff" },
  { channelId: "UCPlWv88ZRMxCcK3BGjrX7ew", name: "Writing on Games" },
  { channelId: "UCNjprNbWKSkb-ukkE7-cS8Q", name: "Xplay" },
];
