---
packages:
  - apps/*
  - packages/*
  - templates/*
allowBuilds:
  "@apollo/protobufjs": true
  "@apollo/rover": true
  "@parcel/watcher": true
  bun: true
  esbuild: true
  msw: true
  protobufjs: true
  sharp: true
  workerd: true
minimumReleaseAge: 0