sonar.projectKey=eglove_ethang-monorepo
sonar.organization=eglove

sonar.sources=\
  apps/ethang-hono/src,\
  apps/sterett-hono/src,\
  packages/eslint-config/src,\
  packages/leetcode/src,\
  packages/markdown-generator/src,\
  packages/store/src,\
  packages/toolbelt/src

sonar.exclusions=\
  **/node_modules/**,\
  **/*.test.ts,\
  **/*.test.tsx,\
  **/*.spec.ts,\
  **/*.spec.tsx,\
  **/e2e/**,\
  **/vitest.config.ts,\
  **/coverage/**

sonar.javascript.lcov.reportPaths=\
  apps/ethang-hono/coverage/lcov.info,\
  apps/sterett-hono/coverage/lcov.info,\
  packages/eslint-config/coverage/lcov.info,\
  packages/leetcode/coverage/lcov.info,\
  packages/markdown-generator/coverage/lcov.info,\
  packages/store/coverage/lcov.info,\
  packages/toolbelt/coverage/lcov.info
