sonar.projectKey=eglove_ethang-monorepo
sonar.organization=eglove

sonar.sources=apps,packages

sonar.exclusions=\
  **/node_modules/**,\
  **/dist/**,\
  **/build/**,\
  **/.next/**,\
  **/.wrangler/**,\
  **/.turbo/**,\
  **/*.test.ts,\
  **/*.test.tsx,\
  **/*.spec.ts,\
  **/*.spec.tsx,\
  **/e2e/**,\
  **/vitest.config.ts,\
  **/coverage/**,\
  packages/eslint-config/src/**/!(*.ts|*.d.ts),\
  **/sw.js,\
  **/routeTree.gen.ts,\
  packages/graphql-types/*.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.issue.ignore.multicriteria=S4782
sonar.issue.ignore.multicriteria.S4782.ruleKey=typescript:S4782
sonar.issue.ignore.multicriteria.S4782.resourceKey=**/*

sonar.coverage.exclusions=packages/service-worker/**
