sonar.projectKey=eglove_ethang-monorepo
sonar.organization=eglove

sonar.sources=\
  apps/sterett-hono/src,\
  packages/eslint-config/src,\
  packages/hono-middleware/src,\
  packages/leetcode/src,\
  packages/markdown-generator/src,\
  packages/store/src,\
  packages/toolbelt/src

sonar.exclusions=\
  **/node_modules/**,\
  **/*.test.ts,\
  **/*.test.tsx,\
  **/*.spec.ts,\
  **/*.spec.tsx,\
  **/e2e/**,\
  **/vitest.config.ts,\
  **/coverage/**,\
  packages/eslint-config/src/**/!(*.ts|*.d.ts)

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.issue.ignore.multicriteria=S4782
sonar.issue.ignore.multicriteria.S4782.ruleKey=typescript:S4782
sonar.issue.ignore.multicriteria.S4782.resourceKey=**/*
