/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const ResumeLazyImport = createFileRoute('/resume')()
const ProjectsLazyImport = createFileRoute('/projects')()
const CoursesLazyImport = createFileRoute('/courses')()
const CertificationsLazyImport = createFileRoute('/certifications')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const ResumeLazyRoute = ResumeLazyImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/resume.lazy').then((d) => d.Route))

const ProjectsLazyRoute = ProjectsLazyImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/projects.lazy').then((d) => d.Route))

const CoursesLazyRoute = CoursesLazyImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/courses.lazy').then((d) => d.Route))

const CertificationsLazyRoute = CertificationsLazyImport.update({
  id: '/certifications',
  path: '/certifications',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/certifications.lazy').then((d) => d.Route),
)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/certifications': {
      id: '/certifications'
      path: '/certifications'
      fullPath: '/certifications'
      preLoaderRoute: typeof CertificationsLazyImport
      parentRoute: typeof rootRoute
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesLazyImport
      parentRoute: typeof rootRoute
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsLazyImport
      parentRoute: typeof rootRoute
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/certifications': typeof CertificationsLazyRoute
  '/courses': typeof CoursesLazyRoute
  '/projects': typeof ProjectsLazyRoute
  '/resume': typeof ResumeLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/certifications': typeof CertificationsLazyRoute
  '/courses': typeof CoursesLazyRoute
  '/projects': typeof ProjectsLazyRoute
  '/resume': typeof ResumeLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/certifications': typeof CertificationsLazyRoute
  '/courses': typeof CoursesLazyRoute
  '/projects': typeof ProjectsLazyRoute
  '/resume': typeof ResumeLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/certifications' | '/courses' | '/projects' | '/resume'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/certifications' | '/courses' | '/projects' | '/resume'
  id:
    | '__root__'
    | '/'
    | '/certifications'
    | '/courses'
    | '/projects'
    | '/resume'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  CertificationsLazyRoute: typeof CertificationsLazyRoute
  CoursesLazyRoute: typeof CoursesLazyRoute
  ProjectsLazyRoute: typeof ProjectsLazyRoute
  ResumeLazyRoute: typeof ResumeLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  CertificationsLazyRoute: CertificationsLazyRoute,
  CoursesLazyRoute: CoursesLazyRoute,
  ProjectsLazyRoute: ProjectsLazyRoute,
  ResumeLazyRoute: ResumeLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/certifications",
        "/courses",
        "/projects",
        "/resume"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/certifications": {
      "filePath": "certifications.lazy.tsx"
    },
    "/courses": {
      "filePath": "courses.lazy.tsx"
    },
    "/projects": {
      "filePath": "projects.lazy.tsx"
    },
    "/resume": {
      "filePath": "resume.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
