import cspell from "@cspell/eslint-plugin";
import keys from "lodash/keys.js";

import { Plugin } from "../build/plugin.ts";
import {
  type CustomRules,
  genRules,
  getNonDeprecatedRules,
} from "./gen-rules.js";

const ruleNames = keys(getNonDeprecatedRules(cspell.rules));

const customRules: CustomRules = [
  {
    name: "spellchecker",
    rule: [
      "error",
      {
        cspell: {
          words: [
            "tauri",
            "Applynetic",
            "julianday",
            "typicode",
            "toolbelt",
            "taze",
            "ethang",
            "TSESTree",
            "Boop",
            "cldr",
            "astro",
            "laravel",
            "qwik",
            "sitecore",
            "uswds",
            "mediat",
            "Packt",
            "Academind",
            "Udemy",
            "Colte",
            "Bootcamp",
            "HTMX",
            "MERN",
            "Nuxt",
            "Credly",
            "Sterett",
            "Beyonder",
            "hotspot",
            "lqip",
            "Hawn",
            "nextui",
            "speculationrules",
            "zustand",
            "vinxi",
            "datasource",
            "turso",
            "supabase",
            "solidjs",
            "labelledby",
            "svix",
            "blockqoute",
            "cortexjs",
            "mathrm",
            "nums",
            "lifecycles",
            "krausest",
            "Signalis",
            "Plass",
            "Iteree",
            "Sonner",
            "cmdk",
            "ngsw",
            "dexie",
            "leetcode",
            "ngsrc",
            "sindresorhus",
            "rogan",
            "heroui",
            "millis",
            "duckdb",
            "pthread",
            "remeda",
            "radash",
            "noto",
            "nosniff",
            "SAMEORIGIN",
            "starcoder",
            "logprobs",
            "sealioning",
            "swebok",
            "pluralsight",
            "skillset",
            "junie",
            "Flexbox",
            "reflogs",
            "Comeau",
            "autodocs",
            "agentic",
            "pico",
            "shiki",
            "vinext",
            "vibing",
            "vibed",
            "Microslop",
            "networkidle",
            "testuser",
            "influencers",
            "headspace",
            "PTSD",
            "inlines",
            "viewports",
            "noopener",
            "noreferrer",
            "hrefs",
            "fetchpriority",
          ],
        },
      },
    ],
  },
];

export const cspellRules = genRules(ruleNames, customRules, "cspell");

export const cspellPlugin = new Plugin({
  files: "**/*.{js,ts,jsx,tsx,cjs,cts,mjs,mts}",
  importString: 'import cspell from "@cspell/eslint-plugin";',
  name: "@cspell/eslint-plugin",
  order: 10,
  pluginName: "cspell",
  pluginValue: "cspell",
  rules: cspellRules,
  url: "https://github.com/streetsidesoftware/cspell/tree/main/packages/cspell-eslint-plugin",
});
