import { Effect } from "effect";
import { InvalidStatusTransitionError } from "../../errors/invalid-status-transition-error.ts";
import { ValidationError } from "../../errors/validation-error.ts";
import { type Status } from "./status.ts";
export type CreateApplicationInput = {
    readonly applicationUrl: string;
    readonly appliedDate: string;
    readonly company: string;
    readonly email: string;
    readonly location?: null | string;
    readonly nextInterviewDate?: null | string;
    readonly notes?: null | string;
    readonly salary?: null | string;
    readonly status?: null | Status;
    readonly title: string;
};
export type JobApplication = {
    readonly applicationUrl: string;
    readonly appliedDate: string;
    readonly company: string;
    readonly createdAt: string;
    readonly email: string;
    readonly id: string;
    readonly location: null | string;
    readonly nextInterviewDate: null | string;
    readonly notes: null | string;
    readonly resumeFilename: null | string;
    readonly resumeKey: null | string;
    readonly resumeSize: null | number;
    readonly salary: null | string;
    readonly status: Status;
    readonly title: string;
    readonly updatedAt: string;
};
export type ResumeAttachment = {
    readonly filename: string;
    readonly key: string;
    readonly size: number;
};
export type UpdateApplicationChanges = {
    readonly appliedDate?: string | undefined;
    readonly company?: string | undefined;
    readonly location?: null | string | undefined;
    readonly nextInterviewDate?: null | string | undefined;
    readonly notes?: null | string | undefined;
    readonly salary?: null | string | undefined;
    readonly status?: null | Status | undefined;
    readonly title?: string | undefined;
};
export declare const createJobApplication: (input: CreateApplicationInput) => Effect.Effect<JobApplication, ValidationError, never>;
export declare const withChanges: (app: JobApplication, changes: UpdateApplicationChanges) => Effect.Effect<{
    appliedDate: string;
    company: string;
    location: string | null;
    nextInterviewDate: string | null;
    notes: string | null;
    salary: string | null;
    status: "applied" | "screening" | "interview" | "offer" | "rejected" | "withdrawn";
    title: string;
    updatedAt: string;
    applicationUrl: string;
    createdAt: string;
    email: string;
    id: string;
    resumeFilename: null | string;
    resumeKey: null | string;
    resumeSize: null | number;
}, ValidationError, never>;
export declare const advanceStatus: (app: JobApplication) => Effect.Effect<never, InvalidStatusTransitionError, never> | Effect.Effect<{
    status: "applied" | "screening" | "interview" | "offer" | "rejected" | "withdrawn";
    updatedAt: string;
    applicationUrl: string;
    appliedDate: string;
    company: string;
    createdAt: string;
    email: string;
    id: string;
    location: null | string;
    nextInterviewDate: null | string;
    notes: null | string;
    resumeFilename: null | string;
    resumeKey: null | string;
    resumeSize: null | number;
    salary: null | string;
    title: string;
}, never, never>;
export declare const attachResume: (app: JobApplication, attachment: ResumeAttachment) => {
    resumeFilename: string;
    resumeKey: string;
    resumeSize: number;
    updatedAt: string;
    applicationUrl: string;
    appliedDate: string;
    company: string;
    createdAt: string;
    email: string;
    id: string;
    location: null | string;
    nextInterviewDate: null | string;
    notes: null | string;
    salary: null | string;
    status: Status;
    title: string;
};
