// @ts-nocheck
import { defineConfig, globalIgnores } from "eslint/config";
import { ignores, languageOptions } from "./constants.js";
import react from "@eslint-react/eslint-plugin";
import reactHooks from "eslint-plugin-react-hooks";

export default defineConfig(globalIgnores(ignores), {
  files: ["**/*.{jsx,tsx}"],
  languageOptions,
  settings: {
    react: { version: "19.2.4" },
  },
  plugins: {
    react: react,
    "react-hooks": reactHooks,
  },
  rules: {
    "react/component-hook-factories": "error",
    "react/error-boundaries": "error",
    "react/exhaustive-deps": "error",
    "react/immutability": "error",
    "react/jsx-dollar": "error",
    "react/jsx-key-before-spread": "error",
    "react/jsx-no-comment-textnodes": "error",
    "react/jsx-shorthand-boolean": "error",
    "react/jsx-shorthand-fragment": "error",
    "react/no-access-state-in-setstate": "error",
    "react/no-array-index-key": "error",
    "react/no-children-count": "error",
    "react/no-children-for-each": "error",
    "react/no-children-map": "error",
    "react/no-children-only": "error",
    "react/no-children-prop": "error",
    "react/no-children-to-array": "error",
    "react/no-class-component": "error",
    "react/no-clone-element": "error",
    "react/no-component-will-mount": "error",
    "react/no-component-will-receive-props": "error",
    "react/no-component-will-update": "error",
    "react/no-context-provider": "error",
    "react/no-create-ref": "error",
    "react/no-direct-mutation-state": "error",
    "react/no-duplicate-key": "error",
    "react/no-forward-ref": "error",
    "react/no-implicit-children": "error",
    "react/no-implicit-key": "error",
    "react/no-implicit-ref": "error",
    "react/no-leaked-conditional-rendering": "error",
    "react/no-missing-component-display-name": "error",
    "react/no-missing-context-display-name": "error",
    "react/no-missing-key": "error",
    "react/no-misused-capture-owner-stack": "error",
    "react/no-nested-component-definitions": "error",
    "react/no-nested-lazy-component-declarations": "error",
    "react/no-redundant-should-component-update": "error",
    "react/no-set-state-in-component-did-mount": "error",
    "react/no-set-state-in-component-did-update": "error",
    "react/no-set-state-in-component-will-update": "error",
    "react/no-unnecessary-use-callback": "error",
    "react/no-unnecessary-use-memo": "error",
    "react/no-unnecessary-use-prefix": "error",
    "react/no-unsafe-component-will-mount": "error",
    "react/no-unsafe-component-will-receive-props": "error",
    "react/no-unsafe-component-will-update": "error",
    "react/no-unstable-context-value": "error",
    "react/no-unstable-default-props": "error",
    "react/no-unused-class-component-members": "error",
    "react/no-unused-props": "error",
    "react/no-unused-state": "error",
    "react/no-use-context": "error",
    "react/no-useless-fragment": "error",
    "react/prefer-destructuring-assignment": "error",
    "react/prefer-namespace-import": "error",
    "react/purity": "error",
    "react/refs": "error",
    "react/rules-of-hooks": "error",
    "react/set-state-in-effect": "error",
    "react/set-state-in-render": "error",
    "react/unstable-rules-of-props": "error",
    "react/unstable-rules-of-state": "error",
    "react/unsupported-syntax": "error",
    "react/use-memo": "error",
    "react/use-state": "error",
    "react-hooks/automatic-effect-dependencies": "error",
    "react-hooks/capitalized-calls": "error",
    "react-hooks/component-hook-factories": "error",
    "react-hooks/config": "error",
    "react-hooks/error-boundaries": "error",
    "react-hooks/exhaustive-deps": "error",
    "react-hooks/fbt": "error",
    "react-hooks/fire": "error",
    "react-hooks/gating": "error",
    "react-hooks/globals": "error",
    "react-hooks/hooks": "error",
    "react-hooks/immutability": "error",
    "react-hooks/incompatible-library": "error",
    "react-hooks/invariant": "error",
    "react-hooks/memoized-effect-dependencies": "error",
    "react-hooks/no-deriving-state-in-effects": "error",
    "react-hooks/preserve-manual-memoization": "error",
    "react-hooks/purity": "error",
    "react-hooks/refs": "error",
    "react-hooks/rule-suppression": "error",
    "react-hooks/rules-of-hooks": "error",
    "react-hooks/set-state-in-effect": "error",
    "react-hooks/set-state-in-render": "error",
    "react-hooks/static-components": "error",
    "react-hooks/syntax": "error",
    "react-hooks/todo": "error",
    "react-hooks/unsupported-syntax": "error",
    "react-hooks/use-memo": "error",
    "react-hooks/void-use-memo": "error",
  },
});
