// @ts-nocheck
import { angularLanguageOptions } from "./constants.js";
import { defineConfig, globalIgnores } from "eslint/config";
import { ignores, languageOptions } from "./constants.js";
import angular from "angular-eslint";
import angularTemplate from "@angular-eslint/eslint-plugin-template";
import angularTS from "@angular-eslint/eslint-plugin";

export default defineConfig(
  globalIgnores(ignores),
  globalIgnores(["**/*.spec.ts", "src/main.server.ts"]),
  {
    files: ["**/*.ts"],
    languageOptions,
    processor: angular.processInlineTemplates,
    plugins: {
      "@angular-eslint": angularTS,
    },
    rules: {
      "@angular-eslint/component-class-suffix": "error",
      "@angular-eslint/component-max-inline-declarations": "error",
      "@angular-eslint/component-selector": [
        "error",
        { prefix: "app", style: "kebab-case", type: "element" },
      ],
      "@angular-eslint/consistent-component-styles": "error",
      "@angular-eslint/contextual-decorator": "error",
      "@angular-eslint/contextual-lifecycle": "error",
      "@angular-eslint/directive-class-suffix": "error",
      "@angular-eslint/directive-selector": [
        "error",
        { prefix: "app", style: "camelCase", type: "attribute" },
      ],
      "@angular-eslint/no-async-lifecycle-method": "error",
      "@angular-eslint/no-attribute-decorator": "error",
      "@angular-eslint/no-developer-preview": "error",
      "@angular-eslint/no-duplicates-in-metadata-arrays": "error",
      "@angular-eslint/no-empty-lifecycle-method": "error",
      "@angular-eslint/no-experimental": "error",
      "@angular-eslint/no-forward-ref": "error",
      "@angular-eslint/no-implicit-take-until-destroyed": "error",
      "@angular-eslint/no-input-prefix": "error",
      "@angular-eslint/no-input-rename": "error",
      "@angular-eslint/no-inputs-metadata-property": "error",
      "@angular-eslint/no-lifecycle-call": "error",
      "@angular-eslint/no-output-native": "error",
      "@angular-eslint/no-output-on-prefix": "error",
      "@angular-eslint/no-output-rename": "error",
      "@angular-eslint/no-outputs-metadata-property": "error",
      "@angular-eslint/no-pipe-impure": "error",
      "@angular-eslint/no-queries-metadata-property": "error",
      "@angular-eslint/no-uncalled-signals": "error",
      "@angular-eslint/pipe-prefix": "error",
      "@angular-eslint/prefer-host-metadata-property": "error",
      "@angular-eslint/prefer-inject": "error",
      "@angular-eslint/prefer-on-push-component-change-detection": "error",
      "@angular-eslint/prefer-output-emitter-ref": "error",
      "@angular-eslint/prefer-output-readonly": "error",
      "@angular-eslint/prefer-signal-model": "error",
      "@angular-eslint/prefer-signals": "error",
      "@angular-eslint/prefer-standalone": "error",
      "@angular-eslint/relative-url-prefix": "error",
      "@angular-eslint/require-lifecycle-on-prototype": "error",
      "@angular-eslint/require-localize-metadata": "error",
      "@angular-eslint/runtime-localize": "error",
      "@angular-eslint/sort-keys-in-type-decorator": "error",
      "@angular-eslint/sort-lifecycle-methods": "error",
      "@angular-eslint/use-component-selector": "error",
      "@angular-eslint/use-component-view-encapsulation": "error",
      "@angular-eslint/use-injectable-provided-in": "error",
      "@angular-eslint/use-lifecycle-interface": "error",
      "@angular-eslint/use-pipe-transform-interface": "error",
    },
  },
  {
    files: ["**/*.html"],
    languageOptions: angularLanguageOptions,
    plugins: {
      "@angular-eslint/template": angularTemplate,
    },
    rules: {
      "@angular-eslint/template/alt-text": "error",
      "@angular-eslint/template/attributes-order": "error",
      "@angular-eslint/template/banana-in-box": "error",
      "@angular-eslint/template/button-has-type": "error",
      "@angular-eslint/template/click-events-have-key-events": "error",
      "@angular-eslint/template/conditional-complexity": "error",
      "@angular-eslint/template/cyclomatic-complexity": "error",
      "@angular-eslint/template/elements-content": "error",
      "@angular-eslint/template/eqeqeq": "error",
      "@angular-eslint/template/i18n": "off",
      "@angular-eslint/template/interactive-supports-focus": "error",
      "@angular-eslint/template/label-has-associated-control": "error",
      "@angular-eslint/template/mouse-events-have-key-events": "error",
      "@angular-eslint/template/no-any": "error",
      "@angular-eslint/template/no-autofocus": "error",
      "@angular-eslint/template/no-call-expression": "off",
      "@angular-eslint/template/no-distracting-elements": "error",
      "@angular-eslint/template/no-duplicate-attributes": "error",
      "@angular-eslint/template/no-empty-control-flow": "error",
      "@angular-eslint/template/no-inline-styles": "error",
      "@angular-eslint/template/no-interpolation-in-attributes": "error",
      "@angular-eslint/template/no-negated-async": "error",
      "@angular-eslint/template/no-nested-tags": "error",
      "@angular-eslint/template/no-positive-tabindex": "error",
      "@angular-eslint/template/prefer-at-else": "error",
      "@angular-eslint/template/prefer-at-empty": "error",
      "@angular-eslint/template/prefer-built-in-pipes": "error",
      "@angular-eslint/template/prefer-class-binding": "error",
      "@angular-eslint/template/prefer-contextual-for-variables": "error",
      "@angular-eslint/template/prefer-control-flow": "error",
      "@angular-eslint/template/prefer-ngsrc": "warn",
      "@angular-eslint/template/prefer-self-closing-tags": "error",
      "@angular-eslint/template/prefer-static-string-properties": "error",
      "@angular-eslint/template/prefer-template-literal": "error",
      "@angular-eslint/template/role-has-required-aria": "error",
      "@angular-eslint/template/table-scope": "error",
      "@angular-eslint/template/use-track-by-function": "error",
      "@angular-eslint/template/valid-aria": "error",
    },
  },
);
