import { DateTime } from "luxon";

const format = "yyyy-MM-dd";

const unsortedLinkList = [
  {
    href: "https://blog.isquaredsoftware.com/2025/06/react-community-2025/",
    published: DateTime.fromFormat("2025-06-13", format),
    quote:
      "However, I've observed and experienced that the React community has had a growing sense of frustrations and disagreements on where React is headed, how it's developed, and the recommended approaches for using React, as well as the interactions between the React team and the community. This in turn overlaps with dozens of different arguments that have ricocheted around the React and general web dev communities in the last few years, as well as specific technical concerns with how React works, comparisons with other similar JS frameworks, and how web apps should be built going forward.",
    title: "The State of React and the Community in 2025",
  },
  {
    href: "https://socket.dev/blog/pnpm-introduces-global-virtual-store-and-expanded-version-catalogs",
    published: DateTime.fromFormat("2025-06-10", format),
    quote:
      "The standout feature in this release is an experimental global virtual store designed to make installs much faster on machines with a warm cache.",
    title:
      "pnpm 10.12 Introduces Global Virtual Store and Expanded Version Catalogs",
  },
  {
    href: "https://overreacted.io/suppressions-of-suppressions/",
    published: DateTime.fromFormat("2025-06-11", format),
    quote:
      "You could introduce another lint rule. This new lint rule would flag attempts to suppress a configurable set of other lint rules. So if the teams that maintain the linter configuration for the parent chain of directories have opinions about which rules really should not be suppressable, trying to suppress those rules will get you one more rule violation—namely, of the rule that prevents those suppressions.",
    title: "Suppressions of Suppressions",
  },
  {
    href: "https://blog.cloudflare.com/cloudflare-service-outage-june-12-2025/",
    published: DateTime.fromFormat("2025-06-12", format),
    quote:
      "On June 12, 2025, Cloudflare suffered a significant service outage that affected a large set of our critical services, including Workers KV, WARP, Access, Gateway, Images, Stream, Workers AI, Turnstile and Challenges, AutoRAG, Zaraz, and parts of the Cloudflare Dashboard.",
    title: "Cloudflare service outage June 12, 2025",
  },
  {
    href: "https://www.thealgorithmicbridge.com/p/new-ai-startup-wants-to-take-your",
    published: DateTime.fromFormat("2025-06-13", format),
    quote:
      "Automation is a good thing if, and only if, 'the ones who dwell' on those soul-crushing jobs are better off after automation has taken hold. The transition must be monitored by people—mediated by incentives—that have as their north star the well-being of the displaced.",
    title: "New AI Startup Wants to Take Your Job ‘as Fast as Possible'",
  },
  {
    href: "https://github.com/AasishPokhrel/shit/issues/1#issue-3138055216",
    published: DateTime.fromFormat("2025-06-11", format),
    quote:
      "We wanted to congratulate you on creating the one billionth repository on GitHub!",
    title:
      "Congratulations on creating the one billionth repository on GitHub!",
  },
  {
    href: "https://blog.google/technology/google-deepmind/ancestra-behind-the-scenes/",
    published: DateTime.fromFormat("2025-06-13", format),
    quote:
      "“ANCESTRA” combined live-action scenes with sequences generated by Veo, our state-of-the-art video generation model. McNitt described her experience working with our technology: 'Veo is another lens through which I get to imagine the universe around me.'",
    title: "Behind “ANCESTRA:” combining Veo with live-action filmmaking",
  },
  {
    href: "https://www.youtube.com/watch?v=7tNuZia4IIc",
    published: DateTime.fromFormat("2025-06-13", format),
    title: "How Rodney The Tree Became A Top Rated Tourist Attraction",
    youtube: {
      id: "7tNuZia4IIc",
      title: "How Rodney The Tree Became A Top Rated Tourist Attraction",
    },
  },
];

// eslint-disable-next-line sonar/no-misleading-array-reverse
export const newsList = unsortedLinkList.sort((a, b) => {
  return b.published.diff(a.published, "millisecond").milliseconds;
});
