/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src\themes\nightowl.ts
 * Command: astryx theme build src\themes\nightowl.ts
 * CLI: @astryxdesign/cli@0.3.0
 * Core: @astryxdesign/core@0.3.0
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const nightowlTheme: DefinedTheme;
