import { urls } from "@ethang/intl/en/urls.ts";

export const SOME_OTHER_D1_ERROR = "Some other D1 error";
export const LOGGER_KEY = "logger-key";
export const SOME_NON_ERROR_OBJECT = "Some non-Error object";

export const FALLBACK = "fallback";
export const REL_ATTR = "@_rel";
export const HREF_ATTR = "@_href";
export const TYPE_ATTR = "@_type";
export const TEXT_KEY = "#text";
export const { EXAMPLE_URL } = urls;
export const TEST_LOGGER_KEY = "test-logger-key";
export const ALTERNATE = "alternate";
export const SELF = "self";
export const { EXAMPLE_ALTERNATE_URL } = urls;
export const { EXAMPLE_FIRST_URL } = urls;
export const TEXT_HTML = "text/html";
export const GUID_123 = "guid-123";
export const GUID_TEXT = "guid-text";
export const ID_123 = "id-123";
export const DESC = "desc";
export const CONTENT_BODY = "content-body";
export const CONTENT_TEXT = "content-text";
export const SUMMARY_TEXT = "summary-text";
export const MY_TITLE = "My Title";
export const OBJECT_TITLE = "Object Title";
export const NO_TITLE = "No Title";
export const FEED_1 = "feed-1";
export const FEED_XML_URL = urls.EXAMPLE_FEED_XML_URL;
export const ENVIRONMENT_TEST = "test";
export const NETWORK_ERROR = "Network Error";
