import type { MarkdownBlock } from "@ethang/markdown-generator/markdown-generator.js";

import { defineSkill } from "../../../define.ts";
import { architectureReference } from "./architecture-reference.ts";
import { tlaPlusReference } from "./tla-plus-reference.ts";

export const specToArchitecture = defineSkill({
  content: [
    {
      level: 1,
      text: "Spec-to-Architecture: BDD to C4 + TLA+ Pipeline",
      type: "header"
    },
    {
      text: "Automatically invoked after `/specification` completes. Reads BDD `.feature` files from the docs directory, generates a C4 Model architecture design (SWEBOK Ch 2/3), and produces a raw TLA+ formal specification (SWEBOK Ch 11) with TLC model checking. This skill is non-interactive — it operates entirely on the artifacts produced by the prior `/specification` phase.",
      type: "text"
    },
    {
      level: 2,
      text: "Quick Decision Tree",
      type: "header"
    },
    {
      code: "Which task?\n├─ Generate architecture design (C4 diagrams) → architecture-reference.md\n├─ Generate TLA+ formal specification → tla-plus-reference.md\n├─ Run TLC model checker → tla-plus-reference.md\n└─ Map BDD scenarios to TLA+ elements → tla-plus-reference.md",
      language: "",
      type: "codeBlock"
    },
    {
      level: 2,
      text: "When to Invoke",
      type: "header"
    },
    {
      text: "This skill is triggered automatically when `/specification` finishes successfully and writes BDD documents to `/docs/<feature-name>/bdd/`. It is NOT invoked via user command. If the specification directory does not exist, the skill halts and informs the user to run `/specification` first.",
      type: "text"
    },
    {
      level: 2,
      text: "Pipeline Stages",
      type: "header"
    },
    {
      text: "The skill executes these stages in order. Each stage depends on the output of the previous stage.",
      type: "text"
    },
    {
      items: [
        {
          text: "**Stage 1 — Validate Inputs**: Check that `/docs/<feature-name>/bdd/` exists and contains at least one valid `.feature` file. Halt with instructions if missing."
        },
        {
          text: "**Stage 2 — Parse BDD**: Parse all `.feature` files (normal-course, exceptions, boundaries) into structured scenarios. Auto-correct malformed Gherkin where possible."
        },
        {
          text: "**Stage 3 — Generate Architecture**: Extract actors, systems, containers, and quality attributes from parsed BDD. Generate C4 System Context and Container diagrams (Mermaid) and write architecture/ files."
        },
        {
          text: "**Stage 4 — Extract TLA+ Model**: Map BDD scenarios to TLA+ constructs. Build VARIABLES from Given clauses, action predicates from Then clauses, temporal properties from sequenced scenarios."
        },
        {
          text: "**Stage 5 — Generate TLA+ Module**: Write `<feature>.tla` with CONSTANTS, VARIABLES, Init, Next, Spec, INVARIANTS, and temporal properties. Generate `<feature>.cfg` with model values."
        },
        {
          text: "**Stage 6 — Run TLC**: Execute `java -cp tla2tools.jar tlc2.TLC -workers 4 -model <feature>`. Monitor for unbounded state space growth."
        },
        {
          text: "**Stage 7 — Auto-Fix Loop**: On TLC failure, diagnose, modify the TLA+ spec, and re-run. Continue while progress is made. Stop and report to the user if no convergence."
        },
        {
          text: "**Stage 8 — Generate Reports**: Write tla-plus/README.md with results and unmapped scenario log. Write architecture/README.md with traceability."
        }
      ],
      type: "numberedList"
    },
    {
      level: 2,
      text: "Output Directory Structure",
      type: "header"
    },
    {
      code: "docs/<feature-name>/\n  ├── requirements.md              (from /specification)\n  ├── bdd/                         (from /specification)\n  │   ├── normal-course.feature\n  │   ├── exceptions.feature\n  │   └── boundaries.feature\n  ├── README.md                    (updated by this skill)\n  ├── architecture/                (generated by Stage 3)\n  │   ├── system-context.md        # C4 Level 1 + Mermaid diagram\n  │   ├── container.md             # C4 Level 2 + Mermaid diagram\n  │   └── README.md                # Architecture overview + quality attribute mapping\n  └── tla-plus/                    (generated by Stages 4–7)\n      ├── <feature>.tla             # Raw TLA+ module\n      ├── <feature>.cfg             # TLC configuration\n      ├── TLC-output.log            # Raw TLC output\n      └── README.md                 # Explanation + unmapped scenarios",
      language: "",
      type: "codeBlock"
    },
    {
      level: 2,
      text: "Failure Mode Handling",
      type: "header"
    },
    {
      headers: ["Failure", "Behavior"],
      rows: [
        [
          "Specification directory missing",
          "Halt. Inform user to run /specification first."
        ],
        [
          "Empty BDD feature files",
          "Halt with warning. No verifiable behavior found."
        ],
        [
          "Malformed Gherkin",
          "Attempt auto-correction. Continue if fixed. Report if not."
        ],
        [
          "Unmappable BDD scenarios",
          "Log as unmapped. Continue with mappable scenarios."
        ],
        ["TLA+ syntax error", "Diagnose, fix, re-run TLC."],
        [
          "Invariant violation",
          "Analyze counterexample, modify spec, re-run TLC."
        ],
        [
          "Deadlock detected",
          "Determine if expected. If not, add fairness or modify Next."
        ],
        [
          "TLC unbounded state",
          "Terminate TLC. Report partial results. Recommend smaller CONSTANTS."
        ],
        [
          "Auto-fix no convergence",
          "Stop loop. Report current state and TLC output to user."
        ],
        [
          "tla2tools.jar missing",
          "Report missing dependency. Still generate .tla and .cfg files."
        ]
      ],
      type: "table"
    },
    {
      level: 2,
      text: "Skill Resources",
      type: "header"
    },
    {
      text: "This skill provides the following reference documents. When the agent needs detailed domain theory, architectural guidance, or TLA+ formal specification techniques, it MUST read the corresponding file from this skill's resources/ directory.",
      type: "text"
    },
    {
      headers: ["Topic", "Reference Document", "Description / Keywords"],
      rows: [
        [
          "C4 Model Architecture Design",
          "[architecture-reference.md](resources/architecture-reference.md)",
          "C4 Context + Container levels, Mermaid diagrams, quality attribute mapping, SWEBOK Ch 2/3 compliance"
        ],
        [
          "TLA+ Formal Specification",
          "[tla-plus-reference.md](resources/tla-plus-reference.md)",
          "TLA+ module structure, BDD-to-TLA+ extraction, TLC config generation, auto-fix loop, SWEBOK Ch 11"
        ]
      ],
      type: "table"
    },
    {
      level: 2,
      text: "SWEBOK v4 References",
      type: "header"
    },
    {
      text: "This skill directly references the following SWEBOK v4 chapters from the `swebok` skill. When the agent needs detailed domain theory, conceptual foundations, or compliance checklists, it MUST read the corresponding file from the swebok skill directory.",
      type: "text"
    },
    {
      items: [
        {
          text: "[requirements-fundamentals.md](../swebok/resources/requirements-fundamentals.md) — Requirements traceability from BDD to architecture and TLA+."
        },
        {
          text: "[architecture-fundamentals.md](../swebok/resources/architecture-fundamentals.md) — Architecture design stage, prescriptive vs descriptive architecture, stakeholders."
        },
        {
          text: "[architecture-description.md](../swebok/resources/architecture-description.md) — C4 Model as an architecture view, ADLs, architecture patterns."
        },
        {
          text: "[design-fundamentals.md](../swebok/resources/design-fundamentals.md) — Design principles (abstraction, modularization, separation of concerns) applied to architecture."
        },
        {
          text: "[testing-fundamentals.md](../swebok/resources/testing-fundamentals.md) — Traceability from requirements to test cases (TLC verification as testing)."
        },
        {
          text: "[models-methods-modeling.md](../swebok/resources/models-methods-modeling.md) — Modeling formalisms, state machines, preconditions/postconditions/invariants."
        },
        {
          text: "[models-methods-types.md](../swebok/resources/models-methods-types.md) — Structural and behavioral modeling types for TLA+ extraction."
        }
      ],
      type: "unorderedList"
    },
    {
      level: 2,
      text: "Compliance Checklist",
      type: "header"
    },
    {
      items: [
        {
          text: "Was the specification directory validated before processing?"
        },
        {
          text: "Were all three BDD feature files (normal-course, exceptions, boundaries) parsed?"
        },
        {
          text: "Does the architecture contain both System Context and Container C4 diagrams?"
        },
        {
          text: "Are quality attributes from non-functional requirements mapped to architectural decisions?"
        },
        {
          text: "Does the TLA+ module include CONSTANTS, VARIABLES, Init, Next, Spec, and INVARIANTS?"
        },
        {
          text: "Does the TLC config assign concrete model values to all CONSTANTS?"
        },
        { text: "Were unmappable scenarios logged with reasons?" },
        { text: "Was TLC executed and results captured?" },
        { text: "Was the auto-fix loop monitored for convergence?" },
        {
          text: "Does the README contain traceability from BDD scenarios to architecture and TLA+ elements?"
        }
      ],
      type: "unorderedList"
    },
    {
      text: "Do not produce any conversational output or solicit user input during pipeline execution. This skill is fully automated and operates on /specification artifacts.",
      type: "text"
    }
  ] as MarkdownBlock[],
  description:
    "Automatically transforms BDD specification documents into a C4 Model architecture design and a formal TLA+ specification with TLC model checking. Runs after /specification completes.",
  name: "spec-to-architecture",
  resources: [
    { content: architectureReference, filename: "architecture-reference.md" },
    { content: tlaPlusReference, filename: "tla-plus-reference.md" }
  ]
});
