import { globSync } from "fast-glob";
import map from "lodash/map.js";
import reduce from "lodash/reduce.js";
import replace from "lodash/replace.js";
import { writeFileSync } from "node:fs";
import { build as tsup } from "tsup";

const CLIENT_GLOB = "src/**/*.client.ts";

const entries = globSync(CLIENT_GLOB);

// Derive the ScriptId for each file: strip "src/" prefix and ".client.ts" suffix.
const scriptIds = map(entries, (entry) =>
  replace(replace(entry, "src/", ""), ".client.ts", ""),
);

// Generate src/generated/script-ids.ts
const unionBody =
  0 === scriptIds.length
    ? "never"
    : map(scriptIds, (id) => `  | "${id}"`).join("\n");

const generated = `// This file is auto-generated by build.ts — do not edit manually.
// Run \`bun build.ts\` (or the deploy script) to regenerate.
// eslint-disable-next-line sonar/redundant-type-aliases
export type ScriptId =
${unionBody};
`;

writeFileSync("src/generated/script-ids.ts", generated, "utf8");

// Build entry map: preserve directory structure relative to src/
// e.g. src/components/navigation/navigation.client.ts
//   → public/scripts/components/navigation/navigation.client.js
const entryMap = reduce(
  entries,
  (accumulator, entry) => {
    const key = replace(replace(entry, "src/", ""), ".ts", "");
    accumulator[key] = entry;
    return accumulator;
  },
  {} as Record<string, string>,
);

if (0 < entries.length) {
  await tsup({
    bundle: true,
    clean: false,
    entry: entryMap,
    format: ["esm"],
    injectStyle: true,
    minify: true,
    noExternal: [/./u],
    outDir: "public/scripts",
    platform: "browser",
    sourcemap: false,
    target: "esnext",
  });
}
