import { globSync } from "fast-glob";
import map from "lodash/map.js";
import reduce from "lodash/reduce.js";
import replace from "lodash/replace.js";
import { writeFileSync } from "node:fs";
import { type Options, build as tsup } from "tsup";

import { buildScriptManifest } from "./src/utilities/build-script-manifest.ts";

const CLIENT_GLOB = "src/**/!(loader).client.ts";
const LOADER_ENTRY = "src/loader.client.ts";

const entries = globSync(CLIENT_GLOB);

// Derive the ScriptId for each file: strip "src/" prefix and ".client.ts" suffix.
const scriptIds = map(entries, (entry) =>
  replace(replace(entry, "src/", ""), ".client.ts", ""),
);

// Generate src/generated/script-ids.ts
const unionBody =
  0 === scriptIds.length
    ? "never"
    : map(scriptIds, (id) => `  | "${id}"`).join("\n");

const generatedIds = `// This file is auto-generated by build.ts — do not edit manually.
// Run \`bun build.ts\` (or the deploy script) to regenerate.
// eslint-disable-next-line sonar/redundant-type-aliases
export type ScriptId =
${unionBody};
`;

writeFileSync("src/generated/script-ids.ts", generatedIds, "utf8");

// Generate src/generated/script-manifest.ts
const manifest = buildScriptManifest(scriptIds);
const manifestEntries = map(
  Object.entries(manifest),
  ([id, url]) => `  "${id}": "${url}"`,
).join(",\n");

const generatedManifest = `// This file is auto-generated by build.ts — do not edit manually.
// Run \`bun build.ts\` (or the deploy script) to regenerate.
import type { ScriptId } from "./script-ids.ts";

export const scriptManifest: Record<ScriptId, string> = {
${manifestEntries},
};
`;

writeFileSync("src/generated/script-manifest.ts", generatedManifest, "utf8");

// Build entry map for feature scripts: preserve directory structure relative to src/
// e.g. src/components/navigation/navigation.client.ts
//   → public/scripts/components/navigation/navigation.client.js
const entryMap = reduce(
  entries,
  (accumulator, entry) => {
    const key = replace(replace(entry, "src/", ""), ".ts", "");
    accumulator[key] = entry;
    return accumulator;
  },
  {} as Record<string, string>,
);

const sharedConfig: Options = {
  bundle: true,
  clean: false,
  format: ["esm"],
  minify: true,
  noExternal: [/./u],
  outDir: "public/scripts",
  platform: "browser",
  sourcemap: false,
  target: "esnext",
};

if (0 < entries.length) {
  await tsup({
    ...sharedConfig,
    entry: entryMap,
    injectStyle: true,
  });
}

// Build the loader separately so it outputs as loader.js (not loader.client.js)
await tsup({
  ...sharedConfig,
  entry: { loader: LOADER_ENTRY },
});
