/**
 * Secrets are set out-of-band via `wrangler secret put` and are intentionally
 * absent from wrangler.jsonc, so `wrangler types` cannot generate bindings for
 * them. Declare them here instead — never edit worker-configuration.d.ts; it is
 * regenerated by `pnpm cf-typegen` and must stay wrangler-owned.
 *
 * These declarations merge into the Env interfaces generated by Wrangler.
 */
declare namespace Cloudflare {
 interface Env {
  /** Token verification secret (set via `wrangler secret put token-auth`). */
  "token-auth": string;
 }
}

interface Env {
 /** Token verification secret (set via `wrangler secret put token-auth`). */
 "token-auth": string;
}
