/**
 * Secrets are set out-of-band (`cf workers secret put`) and are intentionally
 * absent from cloudflare.config.ts, so `cf workers types` cannot generate
 * bindings for them. Declare them here instead - these declarations merge into
 * the Env interface generated by cf.
 */
declare namespace Cloudflare {
  interface Env {
    /** Token verification secret (set via `cf workers secret put token-auth`). */
    "token-auth": string;
  }
}