import type { MarkdownBlock } from "@ethang/markdown-generator/markdown-generator.js";

import { defineRule } from "../../define.ts";

export const securityDomainSpecific = defineRule({
  content: [
    {
      level: 1,
      text: "Domain-Specific Software Security: Cloud, Containers, IoT, and Machine Learning",
      type: "header"
    },
    {
      level: 2,
      text: "1. Domain Theory and Conceptual Foundations",
      type: "header"
    },
    {
      text: "Software security challenges vary significantly across different operational domains. As defined in the IEEE Software Engineering Body of Knowledge (SWEBOK v4), specific domains such as cloud computing, containerized environments, the Internet of Things (IoT), and machine learning (ML) systems introduce unique vulnerabilities and threats. Software engineers must understand these domain-specific characteristics and implement targeted security controls to protect applications, devices, models, and infrastructure.",
      type: "text"
    },
    {
      level: 3,
      text: "1.1 Cloud and Container Security",
      type: "header"
    },
    {
      text: "Cloud infrastructure and virtualization services make provisioning assets inexpensive and fast. However, this flexibility introduces specific management and security risks:",
      type: "text"
    },
    {
      items: [
        {
          text: "**Forgotten Assets and Orphaned Resources**: The ease of provisioning can quickly lead to having many assets strewn across the cloud and eventually forgotten. These forgotten virtual machines, staging databases, serverless functions, or test accounts are a significant security risk, acting as unmonitored entry points that attackers can exploit."
        },
        {
          text: "**Shared Responsibility Model**: A fundamental difference in cloud environments is that physical security is outsourced to the cloud service provider. Developers outsource physical controls such as datacenter cameras, placement of windows, slab-to-slab barriers, anti-tailgating systems, and physical asset tagging. However, the organization remains responsible for securing the virtual network, access configurations, application code, data, database systems, and container configurations."
        },
        {
          text: "**Cloud Configuration Auditing**: A major source of cloud breaches is configuration drift and simple errors (e.g., publicly writable storage buckets, permissive firewall rules, over-privileged IAM roles). Automated cloud security posture management (CSPM) tools are used to detect these flaws."
        },
        {
          text: "**Container Hardening and Orchestration**: Protecting containerized applications requires ensuring base images are minimal (e.g., scratch or alpine), scanning container images for vulnerabilities, restricting container runtimes to avoid root privileges, and isolating containerized processes using namespace controls. Within orchestrators like Kubernetes, engineers must configure network policies, role-based access control (RBAC), and secure pod admission controls."
        }
      ],
      type: "unorderedList"
    },
    {
      level: 3,
      text: "1.2 Internet of Things (IoT) Software Security",
      type: "header"
    },
    {
      text: "The Internet of Things (IoT) connects consumer and industrial devices with backend business IT systems, creating a large, heterogeneous network.\nKey security concerns in the IoT domain include:",
      type: "text"
    },
    {
      items: [
        {
          text: "**Interconnectivity Hazards**: Weakly protected IoT industrial devices are often connected to business IT platforms. If an attacker gains access to business IT networks (for instance, by exploiting browser vulnerabilities or phishing credentials), they can pivot to gain control of weakly protected IoT devices. This can cause severe physical damage and safety incidents in industrial environments."
        },
        {
          text: "**Endpoint Hardening and Physical Security**: IoT devices are often deployed in unsecure physical environments. They must be hardened against physical tampering, debug ports (such as JTAG or UART) must be disabled or protected, and firmware updates must be cryptographically signed and validated using a hardware-based root of trust (such as a Trusted Platform Module - TPM)."
        },
        {
          text: "**Secure Device-to-Device Communication**: Because IoT networks span wide, heterogeneous areas, all device-to-device and device-to-cloud communications must be encrypted and authenticated using secure protocols (e.g., MQTT over TLS, CoAP with DTLS) and unique device certificates (X.509)."
        },
        {
          text: "**Device and Information Credibility**: Ensuring that the data generated by sensors and devices is authentic and has not been falsified."
        },
        {
          text: "**IoT Platform Management**: Utilizing centralized device management tools to monitor device health, rotate credentials, and push security updates."
        }
      ],
      type: "unorderedList"
    },
    {
      level: 3,
      text: "1.3 Machine Learning-Based Application Security",
      type: "header"
    },
    {
      text: "As machine learning (ML) becomes integrated into modern software applications, it introduces specific vulnerabilities that traditional security controls do not address:",
      type: "text"
    },
    {
      items: [
        {
          text: "**Adversarial Machine Learning**: Adversaries can manipulate the inputs or training processes of machine learning models to alter their decisions."
        },
        {
          text: "**Model Poisoning (Training Attacks)**: An attack targeting the training data of a machine learning model. By injecting malicious or skewed data into the training set, attackers compromise the model's learning phase, causing it to make incorrect predictions or create covert backdoors. This can occur in collaborative filtering, federated learning, or online learning systems."
        },
        {
          text: "**Evasion Attacks (Inference Attacks)**: An attack targeting the inputs of a trained machine learning model. Attackers craft subtle, specialized modifications to inputs (adversarial examples) that are imperceptible to humans but cause the trained model to misclassify the input (e.g., modifying a stop sign so a self-driving car model classifies it as a speed limit sign)."
        },
        {
          text: "**Model Security and Intellectual Property Protection**: Preventing model extraction attacks where adversaries query the model repeatedly to reconstruct its internal parameters, stealing intellectual property or analyzing the model for further vulnerabilities:\n- *Membership Inference Attacks*: Determining whether a specific data record was part of the model's training dataset, violating confidentiality and privacy policies.\n- *Model Inversion Attacks*: Reconstructing aspects of the training data by observing model predictions, which can expose sensitive personal details or intellectual property."
        },
        {
          text: "**ML Defenses**: Implementing adversarial training (training models on adversarial examples to increase robustness), input sanitization (filtering out adversarial patterns before input reaches the model), differential privacy (injecting noise during training to hide individual records), rate-limiting model output precision, and implementing cryptographic watermarking to verify model authenticity."
        }
      ],
      type: "unorderedList"
    },
    {
      level: 2,
      text: "2. Compliance Checklist",
      type: "header"
    },
    {
      items: [
        {
          text: "Has the organization established a cloud asset inventory to track and monitor all provisioned virtual resources?"
        },
        {
          text: "Is there an automated policy to decommission and delete temporary, staging, or unused cloud assets to prevent orphaned resources?"
        },
        {
          text: "Has the team defined the boundary of the shared responsibility model, specifying which security controls are outsourced versus managed internally?"
        },
        {
          text: "Are container images scanned for vulnerabilities in the build pipeline before they are pushed to registries?"
        },
        {
          text: "Are container runtimes configured to run processes with the least privilege, avoiding root execution where possible?"
        },
        {
          text: "Has network micro-segmentation been implemented to isolate cloud virtual networks and container namespaces?"
        },
        {
          text: "Do IoT device architectures incorporate endpoint hardening, disabling debug interfaces (e.g., JTAG, UART) in production?"
        },
        {
          text: "Are all IoT device firmware updates cryptographically signed and verified by the device bootloader?"
        },
        {
          text: "Is all device-to-device and device-to-cloud communication encrypted using secure, standard protocols?"
        },
        {
          text: "Have threat modeling sessions analyzed the pivot paths from business IT networks to industrial IoT control networks?"
        },
        {
          text: "Are device authentication credentials unique per device and managed using a secure, central IoT platform?"
        },
        {
          text: "Has a data validation framework been established to verify the credibility and integrity of sensor data generated by IoT devices?"
        },
        {
          text: "Are machine learning pipeline training datasets audited to prevent model poisoning attacks?"
        },
        {
          text: "Is training data collected from trusted sources, and is its provenance tracked and verified?"
        },
        {
          text: "Are machine learning models tested against adversarial inputs to evaluate their resilience to evasion attacks?"
        },
        {
          text: "Are model access interfaces rate-limited and monitored to prevent model extraction and inversion attacks?"
        },
        {
          text: "Are machine learning model deployments treated as software assets, with version control and automated rollback capabilities?"
        },
        {
          text: "Is there a process to monitor machine learning model decisions for drift and anomalous behavior in production?"
        },
        {
          text: "Have safety overrides and fail-secure defaults been implemented for IoT systems to prevent safety incidents if control is compromised?"
        },
        {
          text: "Are cloud configurations audited continuously using automated CSPM tools to detect misconfigurations?"
        },
        {
          text: "Do containers use minimal base images (such as scratch or alpine) to reduce the system's attack surface?"
        },
        {
          text: "Are IoT devices protected by hardware-based roots of trust (like TPMs) to ensure secure boot sequences?"
        },
        {
          text: "Are machine learning predictions sanitized and bounding checks applied to model outputs before they trigger system actions?"
        },
        {
          text: "Has the team implemented differential privacy techniques on training data to prevent membership inference attacks?"
        },
        {
          text: "Are IoT device communications authenticated using mutual TLS (mTLS) with unique X.509 client certificates?"
        },
        {
          text: "Does the organization perform regular audits to verify that no orphaned or forgotten assets exist in cloud tenancies?"
        },
        {
          text: "Are Kubernetes role-based access control (RBAC) rules configured to restrict access to the minimum required namespaces?"
        },
        {
          text: "Are cloud databases configured to encrypt sensitive data at rest and protect backups from unauthorized access?"
        },
        {
          text: "Does the organization restrict and log all administrative access to production cloud environments?"
        }
      ],
      type: "unorderedList"
    }
  ] as MarkdownBlock[],
  description:
    "domain-specific software security, cloud security, container security, forgotten assets, shared responsibility model, container hardening, IoT security, Internet of Things, endpoint hardening, device-to-device communication, device credibility, IoT platform management, machine learning security, model poisoning, evasion attack, adversarial input, model extraction",
  filename: "security-domain-specific",
  trigger: "model_decision"
});
