name: CI
on:
  push:
    branches:
      - dev
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"
      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install Dependencies
        run: pnpm install
      - name: Install Playwright
        run: pnpx playwright install --with-deps
      - name: Build
        run: pnpm run build
      - name: Run Tests
        run: pnpm run test
      - name: Run lint
        run: pnpm run lint
  merge:
    name: Auto-Merge
    needs: ci
    runs-on: ubuntu-latest
    if: ${{ success() }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
      - name: Merge dev into main
        run: |
          git fetch origin
          git checkout main
          git merge origin/dev
          git push origin main